export const jqxLocalization = {
  pagergotopagestring: 'Страница:',
  pagershowrowsstring: 'Строк на странице:',
  pagerrangestring: ' из ',
  pagerpreviousbuttonstring: 'назад',
  pagernextbuttonstring: 'вперед',
  pagerfirstbuttonstring: 'первая',
  pagerlastbuttonstring: 'последняя',
  groupsheaderstring: 'Перетащите столбец сюда для группировки по нему',
  sortascendingstring: 'Сортировать по возрастанию',
  sortdescendingstring: 'Сортировать по убыванию',
  sortremovestring: 'Очистить сортировку',
  groupbystring: 'Группировать по этому столбцу',
  groupremovestring: 'Убрать из группировки',
  filterclearstring: 'Сбросить фильтр',
  filterstring: 'Фильтр',
  filtershowrowstring: 'Показать строки где:',
  filterorconditionstring: 'Или',
  filterandconditionstring: 'И',
  filterselectallstring: '(Все)',
  filterchoosestring: 'Выберите фильтр:',
  filterstringcomparisonoperators: [
    'пустой',
    'не пустой',
    'содержит',
    'содержит(с учётом регистра)',
    'не содержит',
    'не содержит(с учётом регистра)',
    'начинается с',
    'начинается с(с учётом регистра)',
    'заканчивается на',
    'заканчивается на(с учётом регистра)',
    'равно',
    'равно(с учётом регистра)',
    'null',
    'не null',
  ],
  filternumericcomparisonoperators: [
    'равно',
    'не равно',
    'меньше',
    'меньше или равно',
    'больше',
    'больше или равно',
    'null',
    'пусто',
  ],
  filterbooleancomparisonoperators: ['равно', 'не равно'],
  filterdatecomparisonoperators: [
    'равно',
    'не равно',
    'меньше',
    'меньше или равно',
    'больше',
    'больше или равно',
    'null',
    'пусто',
  ],
  emptydatastring: 'Нет данных',
  clearstring: 'Сброс',
  todaystring: 'Сегодня',
  loadtext: 'Загрузка...',
  firstDay: 1,
  dayViewString: 'День',
  weekViewString: 'Неделя',
  monthViewString: 'Месяц',
  days: {
    names: [
      'Воскресенье',
      'Понедельник',
      'Вторник',
      'Среда',
      'Четверг',
      'Пятница',
      'Суббота',
    ],
    namesAbbr: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
    namesShort: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
  },
  months: {
    names: [
      'Январь',
      'Февраль',
      'Март',
      'Апрель',
      'Май',
      'Июнь',
      'Июль',
      'Август',
      'Сентябрь',
      'Октябрь',
      'Ноябрь',
      'Декабрь',
      '',
    ],
    namesAbbr: ['Янв', 'Фев', 'Мар', 'Апр', 'Май', 'Июн', 'Июл', 'Авг', 'Сен', 'Окт', 'Ноя', 'Дек', ''],
  },
  patterns: {
    d: 'dd.MM.yyyy',
    D: 'dddd, dd MMMM yyyy',
    t: 'HH:mm',
    T: 'HH:mm:ss',
    f: 'dddd, dd MMMM yyyy HH:mm',
    F: 'dddd, dd MMMM yyyy HH:mm:ss',
    M: 'dd MMMM',
    Y: 'MMMM yyyy',
  },
} as const

export const jqxLocale = 'ru-RU'
