export const jqxLocalization = {
  pagergotopagestring: 'Страница:',
  pagershowrowsstring: 'Строк на странице:',
  pagerrangestring: ' из ',
  pagerpreviousbuttonstring: 'назад',
  pagernextbuttonstring: 'вперед',
  pagerfirstbuttonstring: 'первая',
  pagerlastbuttonstring: 'последняя',
  groupsheaderstring: 'Перетащите столбец сюда для группировки по нему',
  sortascendingstring: 'Сортировать по возрастанию',
  sortdescendingstring: 'Сортировать по убыванию',
  sortremovestring: 'Очистить сортировку',
  groupbystring: 'Группировать по этому столбцу',
  groupremovestring: 'Убрать из группировки',
  filterclearstring: 'Сбросить фильтр',
  filterstring: 'Фильтр',
  filtershowrowstring: 'Показать строки где:',
  filterorconditionstring: 'Или',
  filterandconditionstring: 'И',
  filterselectallstring: '(Все)',
  filterchoosestring: 'Выберите фильтр:',
  filterstringcomparisonoperators: [
    'пустой',
    'не пустой',
    'содержит',
    'содержит(с учётом регистра)',
    'не содержит',
    'не содержит(с учётом регистра)',
    'начинается с',
    'начинается с(с учётом регистра)',
    'заканчивается на',
    'заканчивается на(с учётом регистра)',
    'равно',
    'равно(с учётом регистра)',
    'null',
    'не null',
  ],
  filternumericcomparisonoperators: [
    'равно',
    'не равно',
    'меньше',
    'меньше или равно',
    'больше',
    'больше или равно',
    'null',
    'пусто',
  ],
  filterbooleancomparisonoperators: ['равно', 'не равно'],
  filterdatecomparisonoperators: [
    'равно',
    'не равно',
    'меньше',
    'меньше или равно',
    'больше',
    'больше или равно',
    'null',
    'пусто',
  ],
  emptydatastring: 'Нет данных',
  clearstring: 'Сброс',
  todaystring: 'Сегодня',
  loadtext: 'Загрузка...',
} as const

export const jqxLocale = 'ru-RU'
