export const jqxLocalization = {
  pagergotopagestring: 'Страница:',
  pagershowrowsstring: 'Строк на странице:',
  pagerrangestring: ' из ',
  pagerpreviousbuttonstring: 'назад',
  pagernextbuttonstring: 'вперед',
  pagerfirstbuttonstring: 'первая',
  pagerlastbuttonstring: 'последняя',
  groupsheaderstring: 'Перетащите столбец сюда для группировки по нему',
  sortascendingstring: 'Сортировать по возрастанию',
  sortdescendingstring: 'Сортировать по убыванию',
  sortremovestring: 'Очистить сортировку',
  groupbystring: 'Группировать по этому столбцу',
  groupremovestring: 'Убрать из группировки',
  filterclearstring: 'Сбросить фильтр',
  filterstring: 'Фильтр',
  filtershowrowstring: 'Показать строки где:',
  filterorconditionstring: 'Или',
  filterandconditionstring: 'И',
  filterselectallstring: '(Все)',
  filterchoosestring: 'Выберите фильтр:',
  filterstringcomparisonoperators: [
    'пустой',
    'не пустой',
    'содержит',
    'содержит(с учётом регистра)',
    'не содержит',
    'не содержит(с учётом регистра)',
    'начинается с',
    'начинается с(с учётом регистра)',
    'заканчивается на',
    'заканчивается на(с учётом регистра)',
    'равно',
    'равно(с учётом регистра)',
    'null',
    'не null',
  ],
  filternumericcomparisonoperators: [
    'равно',
    'не равно',
    'меньше',
    'меньше или равно',
    'больше',
    'больше или равно',
    'null',
    'пусто',
  ],
  filterbooleancomparisonoperators: ['равно', 'не равно'],
  filterdatecomparisonoperators: [
    'равно',
    'не равно',
    'меньше',
    'меньше или равно',
    'больше',
    'больше или равно',
    'null',
    'пусто',
  ],
  emptydatastring: 'Нет данных',
  clearstring: 'Сброс',
  todaystring: 'Сегодня',
  loadtext: 'Загрузка...',
  emptyDataString: 'Нет данных для отображения',
  clearString: 'Сброс',
  todayString: 'Сегодня',
  loadString: 'Загрузка...',
  agendaDateColumn: 'Дата',
  agendaTimeColumn: 'Время',
  agendaAppointmentColumn: 'Событие',
  agendaAllDayString: 'Весь день',
  backString: 'Назад',
  forwardString: 'Вперед',
  toolBarPreviousButtonString: 'Предыдущий',
  toolBarNextButtonString: 'Следующий',
  firstDay: 1,
  dayViewString: 'День',
  weekViewString: 'Неделя',
  monthViewString: 'Месяц',
  agendaViewString: 'Повестка',
  timelineDayViewString: 'Лента (день)',
  timelineWeekViewString: 'Лента (неделя)',
  timelineMonthViewString: 'Лента (месяц)',
  editRecurringAppointmentDialogTitleString: 'Редактировать повтор',
  editRecurringAppointmentDialogContentString: 'Изменить только это событие или всю серию?',
  editRecurringAppointmentDialogOccurrenceString: 'Только это событие',
  editRecurringAppointmentDialogSeriesString: 'Всю серию',
  editDialogTitleString: 'Редактировать событие',
  editDialogCreateTitleString: 'Создать событие',
  contextMenuEditAppointmentString: 'Редактировать событие',
  contextMenuCreateAppointmentString: 'Создать событие',
  editDialogSubjectString: 'Тема',
  editDialogLocationString: 'Место',
  editDialogFromString: 'С',
  editDialogToString: 'По',
  editDialogAllDayString: 'Весь день',
  editDialogDescriptionString: 'Описание',
  editDialogStatusString: 'Статус',
  editDialogStatuses: {
    free: 'Свободно',
    tentative: 'Предварительно',
    busy: 'Занято',
    outOfOffice: 'Нет на месте',
    Free: 'Свободно',
    Tentative: 'Предварительно',
    Busy: 'Занято',
    'Out of Office': 'Нет на месте',
  },
  editDialogResourceIdString: 'Календарь',
  editDialogTimeZoneString: 'Часовой пояс',
  editDialogSelectTimeZoneString: 'Выберите часовой пояс',
  editDialogColorString: 'Цвет',
  editDialogColorPlaceHolderString: 'Выберите цвет',
  editDialogSaveString: 'Сохранить',
  editDialogCancelString: 'Отмена',
  editDialogDeleteString: 'Удалить',
  editDialogRepeatString: 'Повтор',
  editDialogRepeatEveryString: 'Повторять каждые',
  editDialogRepeatEveryWeekString: 'нед.',
  editDialogRepeatEveryYearString: 'г.',
  editDialogRepeatEveryDayString: 'дн.',
  editDialogRepeatEveryMonthString: 'мес.',
  editDialogRepeatNeverString: 'Никогда',
  editDialogRepeatDailyString: 'Ежедневно',
  editDialogRepeatWeeklyString: 'Еженедельно',
  editDialogRepeatMonthlyString: 'Ежемесячно',
  editDialogRepeatYearlyString: 'Ежегодно',
  editDialogRepeatEveryMonthDayString: 'День',
  editDialogRepeatFirstString: 'Первый',
  editDialogRepeatSecondString: 'Второй',
  editDialogRepeatThirdString: 'Третий',
  editDialogRepeatFourthString: 'Четвертый',
  editDialogRepeatLastString: 'Последний',
  editDialogRepeatEndString: 'Окончание',
  editDialogRepeatAfterString: 'После',
  editDialogRepeatOnString: 'В',
  editDialogRepeatOfString: 'из',
  editDialogRepeatOccurrencesString: 'повтор(ений)',
  editDialogRepeatSaveString: 'Сохранить событие',
  editDialogRepeatSaveSeriesString: 'Сохранить серию',
  editDialogRepeatDeleteString: 'Удалить событие',
  editDialogRepeatDeleteSeriesString: 'Удалить серию',
  editDialogExceptionsString: 'Исключения',
  editDialogResetExceptionsString: 'Сбросить исключения',
  days: {
    names: [
      'Воскресенье',
      'Понедельник',
      'Вторник',
      'Среда',
      'Четверг',
      'Пятница',
      'Суббота',
    ],
    namesAbbr: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
    namesShort: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
  },
  months: {
    names: [
      'Январь',
      'Февраль',
      'Март',
      'Апрель',
      'Май',
      'Июнь',
      'Июль',
      'Август',
      'Сентябрь',
      'Октябрь',
      'Ноябрь',
      'Декабрь',
      '',
    ],
    namesAbbr: ['Янв', 'Фев', 'Мар', 'Апр', 'Май', 'Июн', 'Июл', 'Авг', 'Сен', 'Окт', 'Ноя', 'Дек', ''],
  },
  patterns: {
    d: 'dd.MM.yyyy',
    D: 'dddd, dd MMMM yyyy',
    t: 'HH:mm',
    T: 'HH:mm:ss',
    f: 'dddd, dd MMMM yyyy HH:mm',
    F: 'dddd, dd MMMM yyyy HH:mm:ss',
    M: 'dd MMMM',
    Y: 'MMMM yyyy',
  },
} as const

export const jqxLocale = 'ru-RU'
